### ISSUE TITLE
Question in using "Global" option

### ISSUE THREAD

**Issue by hc464** [tholden/dynareOBC#7]
Dear Professor Holden,

Hope everything is going on very well with you. This is Hao Chang, a PhD candidate in Finance at the State University on New Jersey. Thank you so much for your hard work on developing "dynareOBC" toolkit, which is extremely helpful for my research. 

I want to use the "Global" option of dynareOBC. Following the readme, I input the following line to matlab:

dynareOBC bkw2012.mod Global

But then the matlab report the error "You cannot specify both the NoCubature and the Global options." Could you tell me the right way to use "Global" option?

My second question is: as time(policy)-iteration is another method to obtain a global solution of DSGE model. How does the "dynareOBC" with "Global Option" compared with the time(policy)-iteration method? Besides the difference between the computational efficiency and methods, can these two methods realize the same goal?

My last question is: is it possible to use "dynareOBC" toolkit to perform the simulation to show the "cross-sectional" changes of endogenous variables based on the change of exogenous variable? For example, in the classic NK model, if we assume subjective discount rate (beta) is exogenous, could we use the toolkit to get the corresponding observations of consumption and inflation when the beta is set to be different values?

Thank you very much again. I am looking forward to hearing and learning from you.

Best Regards,
Hao Chang

**Comment by tholden** [comment]
With Global you need to specify a cubature option, e.g. FastCubature. That error message is not very helpful I know. It's fixed in c5e953c6149887a6ac28c7ea5726ca4c01f0cda9 .
The Global option is not a traditional time iteration (it's a kind of hybrid method) and it's strictly experimental at this time. I'm afraid there's not a lot of documentation for it at present. I would not use it without extensive testing that it actually improves accuracy on your particular problem.
You could certainly perform "comparative statics" exercises like the one you describe. Just simulate with different values of the parameter.

**Comment by hc464** [comment]
Dear Professor Holden,

Thank you so much for your advises. They are very helpful!

Best Regards,
Hao
